#!/usr/bin/python




def BKDRHash(s):
	'''BKDR Hash is an algorithm invented by Brian Kernighan, Dennis Ritchie.
		The algorithm was presented in/on "The C Programming Language".
		The digest (hash generated by this algorithm) is 32 bits (4 Bytes) in length.
		refer to: http://www.partow.net/programming/hashfunctions/
	'''
	seed = 131  # can be any combination of 31, like 31 131 1313 13131 131313
	hash = 0
	for i in range(len(s)):
		hash = (hash * seed) + ord(s[i])
	return hash

if __name__ == '__main__':
	cleartext = "This is a test string for use with the BKDRHash"
	print BKDRHash(cleartext)